version: '3'
services:
  app:
    image: webdevtoolsandtech/currency-backend
    ports:
      - 80
    environment:
      REDIS_ADDRESS: 'redis:6379'
      SESSION_SECRET: 'sshhhhh'
      USER_SERVICE_ADDRESS: 'user-service'
      FRONTEND_ADDRESS: 'currency-frontend'
      CALCULATOR_ADDRESS: 'currency-calculator'  

  redis:
    image: redis:alpine
    ports:
      - 6379

  user-service:
    image: webdevtoolsandtech/user-service
    ports:
      - 80
    environment:
      REDIS_ADDRESS: 'redis:6379'

  currency-frontend:
    image: webdevtoolsandtech/currency-frontend
    ports:
      - 80
    
  currency-calculator:
    image: webdevtoolsandtech/currency-calculator
    ports: 
      - 80
